name: Manhunt
version: 1.0.0
main: com.linchen.manhunt.Manhunt
api-version: 1.16

commands:
  manhunt:
    description: Manhunt game command
    usage: /manhunt <start|end|help> [args]
    permission: manhunt.admin

permissions:
  manhunt.admin:
    description: Permission to use manhunt commands
    default: op